# Generated by Django 4.0.2 on 2022-02-08 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatapi', '0003_rename_reciever_conversation_receiver'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
